// Vercel build step: writes config.js from environment variables.
//   FACESYNC_API_URL      = https://your-api.onrender.com                        (required)
//   FACESYNC_ARCFACE_URL  = https://huggingface.co/<you>/<repo>/resolve/main/arcface_r100.onnx  (required)
const fs = require("fs");
const path = require("path");

function fail(msg) {
  console.error("\n[build-config] ERROR: " + msg + "\n");
  process.exit(1);
}

const api = (process.env.FACESYNC_API_URL || "").trim().replace(/\/+$/, "");
if (!api) fail("FACESYNC_API_URL is not set.\nSet it in Vercel -> Project -> Settings -> Environment Variables, e.g.\n  FACESYNC_API_URL = https://facesync-api.onrender.com");
if (!/^https:\/\//.test(api)) fail(`FACESYNC_API_URL must start with https:// (got "${api}")`);

const arc = (process.env.FACESYNC_ARCFACE_URL || "").trim();
if (!arc) fail("FACESYNC_ARCFACE_URL is not set.\nIt is the public link of your converted model (arcface_r100.onnx), e.g.\n  https://huggingface.co/YOUR_NAME/facesync-arcface/resolve/main/arcface_r100.onnx\nSee DEPLOYMENT.md step 2.");
if (!/^https:\/\//.test(arc)) fail(`FACESYNC_ARCFACE_URL must start with https:// (got "${arc}")`);

const out = `/* Generated by build-config.js - do not edit. */
window.FACESYNC_CONFIG = ${JSON.stringify({ API_BASE: api, ARCFACE_URL: arc }, null, 2)};
`;
fs.writeFileSync(path.join(__dirname, "config.js"), out);
console.log(`[build-config] API_BASE     = ${api}`);
console.log(`[build-config] ARCFACE_URL  = ${arc}`);
